backend/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views import defaults as default_views

urlpatterns = [
    # admin
    path(settings.ADMIN_URL, admin.site.urls),
    # user and account mgmt
    path("user/", include("ratemyderp.users.urls")),
    path("accounts/", include("allauth.urls")),
    # ratemyderp apps
    path("", include("ratemyderp.pages.urls")),
    path("derp/", include("ratemyderp.derps.urls")),
    path("rate/", include("ratemyderp.rating.urls")),
    path("profile/", include("ratemyderp.profiles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

backend/ratemyderp/derps/urls.py
from django.urls import path
from ratemyderp.derps.views import (
    derp_detail_view,
    derp_create_view,
    derp_delete_view,
    derp_share_view,
)

app_name = "derp"
urlpatterns = [
    path(route="<uuid:pk>", view=derp_detail_view, name="detail"),
    path(route="submit", view=derp_create_view, name="submit"),
    path(route="<uuid:pk>/delete", view=derp_delete_view, name="delete"),
    path(route="<uuid:pk>/share", view=derp_share_view, name="share"),
]

backend/ratemyderp/pages/urls.py
from django.urls import path
from ratemyderp.pages.views import noderps_page_view, about_page_view
from ratemyderp.derps.views import top10_derps_view
from ratemyderp.rating.views import go_rating_view

urlpatterns = [
    path("noderps", noderps_page_view, name="noderps"),
    path("top10", top10_derps_view, name="top10"),
    path("", go_rating_view, name="go-rate"),
    path("about", about_page_view, name="about"),
]

backend/ratemyderp/profiles/urls.py
from django.urls import path
from ratemyderp.profiles.views import (
    user_profile_view,
    user_profile_update_view,
)

app_name = "profile"
urlpatterns = [
    path(
        route="settings",
        view=user_profile_update_view,
        name="settings",
    ),
    path(route="user/<str:username>", view=user_profile_view, name="detail"),
]

backend/ratemyderp/users/urls.py
from django.urls import path, include
from ratemyderp.users.views import user_redirect_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
]

backend/ratemyderp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import post_save


class DerpUser(AbstractUser):
    """
    Custom user model for RateMyDerp!
    When adding fields which need to be filled out at signup, don't forget
    to modify forms.SignupForm and forms.SocialSignupForm accordingly
    """

    # accommodate patterns other than first + last name
    name = models.CharField("Name", blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("profile:detail", kwargs={"username": self.username})


# ----------------------- User -> Create Profile Signal ---------------------- #
@receiver(post_save, sender=DerpUser)
def instantiate_user_profile(sender, instance, created, **kwargs):
    from ratemyderp.profiles.models import DerpUserProfile

    if created:
        profile = DerpUserProfile(user=instance)
        profile.save()

backend/ratemyderp/derps/forms.py
from django.forms import (
  ModelForm, 
  RadioSelect, 
  Textarea,
  FileInput
)
from ratemyderp.derps.models import Derp

class DerpForm(ModelForm):
  class Meta:
    model = Derp
    fields = [
      'name', 'image', 'species', 'age_when_added', 'bio'
    ]
    widgets = {
      'species': RadioSelect,
      'bio': Textarea(attrs={'rows': 4}),
      'image': FileInput(attrs={'class': 'image-upload'})
    }

    # TODO: validate name does not already exist; must be unique
    # eg https://www.agiliq.com/blog/2019/01/django-createview/

backend/ratemyderp/profiles/forms.py
from django.forms import ModelForm, Textarea, FileInput

from ratemyderp.profiles.models import DerpUserProfile


class DerpUserProfileForm(ModelForm):
    class Meta:
        model = DerpUserProfile
        fields = ["avatar", "is_private", "bio"]
        widgets = {
            "avatar": FileInput(attrs={"class": "image-upload"}),
            "bio": Textarea(attrs={"rows": 4}),
        }

backend/ratemyderp/rating/forms.py
from django.forms import ModelForm, NumberInput

from ratemyderp.rating.models import DerpRating


class RatingForm(ModelForm):
    class Meta:
        model = DerpRating
        fields = [
            "value",
        ]
        widgets = {
            "value": NumberInput(
                attrs={"type": "range", "step": "1", "min": "1", "max": "10"}
            )
        }

backend/ratemyderp/users/forms.py
# ---------------------------------------------------------------------------- #
#                                Users App Forms                               #
# ---------------------------------------------------------------------------- #

from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms


class DerpUserCreationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)

class DerpUserAdminChangeForm(admin_forms.UserChangeForm):
    """
    Admin change form for custom DerpUser
    """
    class Meta(admin_forms.UserChangeForm.Meta):
        model = get_user_model()


class DerpUserChangeForm(UserChangeForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username',)


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Custom DerpUser admin area creation form
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = get_user_model()
        error_messages = {
            "username": {"unique": "That username is already taken."}
        }

class DerpUserSignupForm(SignupForm):
  """
  Rendered by accounts signup view. Default fields automatically added.
  """

backend/ratemyderp/derps/views.py
from django.views.generic import DetailView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404

from ratemyderp.derps.models import Derp
from ratemyderp.derps.forms import DerpForm
from ratemyderp.rating.models import DerpRating
from ratemyderp.utils.sessions import UserOrAnon


class DerpCreateView(LoginRequiredMixin, CreateView):
    form_class = DerpForm
    model = Derp

    # inject owner fkey after form validation occurs
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


derp_create_view = DerpCreateView.as_view()


class DerpDetailView(DetailView):
    model = Derp

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # add existing rating from this user to template context, if it exists
        if self.request.user is not None:
            existing_rating = DerpRating.get_existing_or_none(
                self.request.user, self.get_object()
            )
            ctx["user_rating"] = (
                existing_rating.value if existing_rating is not None else None
            )
        return ctx

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        # increment visit counter for this Derp
        user = UserOrAnon.from_request(request)
        self.object.increment_visit_count(user)
        return res


derp_detail_view = DerpDetailView.as_view()


class DerpShareView(DetailView):
    model = Derp
    template_name = "derps/derp_share.html"

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        # increment the share counter for this Derp
        self.get_object().increment_share_count()
        return res


derp_share_view = DerpShareView.as_view()


class Top10DerpsView(ListView):
    model = Derp
    template_name = "derps/derps_top10.html"
    queryset = Derp.objects.all().order_by("-rating_val")[:10]
    context_object_name = "derps"


top10_derps_view = Top10DerpsView.as_view()


class DerpDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Derp
    template_name = "derps/derp_delete.html"
    success_message = ""

    def get_object(self, queryset=None):
        derp = super(DerpDeleteView, self).get_object()
        self.user = self.request.user
        if derp.owner != self.user:
            raise Http404
        return derp

    def get_success_url(self):
        return self.user.get_absolute_url()

    def get_success_message(self, cleaned_data):
        return f"Deleted {self.object.name} successfully."


derp_delete_view = DerpDeleteView.as_view()

backend/ratemyderp/pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"


home_page_view = HomePageView.as_view()


class NoDerpsPageView(TemplateView):
    template_name = "pages/noderps.html"


noderps_page_view = NoDerpsPageView.as_view()


class AboutPageView(TemplateView):
    template_name = "pages/about.html"


about_page_view = AboutPageView.as_view()

backend/ratemyderp/profiles/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from ratemyderp.profiles.models import DerpUserProfile
from ratemyderp.profiles.forms import DerpUserProfileForm
from ratemyderp.derps.models import Derp

User = get_user_model()


class UserProfileView(ListView):
    model = Derp
    template_name = "profiles/profile_detail.html"
    context_object_name = "derps"
    paginate_by = 6

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = get_object_or_404(User, username=kwargs["username"])
        self.queryset = Derp.objects.filter(owner=self.user)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # we add the user's profile to the context (which already
        # contains their paginated derplist)
        ctx["profile"] = DerpUserProfile.objects.get(user=self.user)
        return ctx


user_profile_view = UserProfileView.as_view()


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):

    model = DerpUserProfile
    template_name = "profiles/profile_update.html"
    form_class = DerpUserProfileForm
    context_object_name = "profile"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = request.user

    def get_object(self):
        profile = get_object_or_404(DerpUserProfile, user=self.user)
        return profile


user_profile_update_view = UserProfileUpdateView.as_view()

backend/ratemyderp/rating/views.py
from django.shortcuts import redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.views import View
from django.views.generic.base import RedirectView

from ratemyderp.derps.models import Derp
from ratemyderp.rating.models import DerpRating
from ratemyderp.utils.sessions import UserOrAnon
from ratemyderp.rating.forms import RatingForm

User = get_user_model()


class GoRatingView(RedirectView):
    """
    The main "Go Rating" app view.
    Presents the user with a Derp to rate and will only generate
    a fresh one to see if they vote on the currently displayed one.
    """

    def get_redirect_url(self, *args, **kwargs):
        user = UserOrAnon.from_request(self.request)
        derp_to_rate = (
            Derp.get_fresh_or_none(user)
            if user.get_next_derp_id_to_rate() == None
            else Derp.get_by_uuid(user.get_next_derp_id_to_rate())
        )
        self.url = (
            derp_to_rate.get_absolute_url()
            if derp_to_rate is not None
            else "/noderps"
        )
        return super().get_redirect_url(*args, **kwargs)


go_rating_view = GoRatingView.as_view()


class FreshRandomDerpView(RedirectView):
    """
    Redirects user to a new randomly selected derp, or to the noderps
    page if the user has exhausted all fresh derps to vote on
    """

    def get_redirect_url(self, *args, **kwargs):
        user = UserOrAnon.from_request(self.request)
        fresh_derp = Derp.get_fresh_or_none(user)
        self.url = (
            fresh_derp.get_absolute_url()
            if fresh_derp is not None
            else "/noderps"
        )
        return super().get_redirect_url(*args, **kwargs)


fresh_random_derp_view = FreshRandomDerpView.as_view()


class RateDerpView(View):
    """
    Handles GET or POST from user to rate derps.
    Presents the user with a new derp to rate only if they
    have just completed rating the one presented. This is done
    by returning fresh_random_derp_view when a rating is received.
    """

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.derp = Derp.get_by_uuid(kwargs["derp_uuid"])

    def get(self, request, *args, **kwargs):
        return redirect(self.derp.get_absolute_url())

    def post(self, request, *args, **kwargs):
        form = RatingForm(request.POST)
        # we're just using the form for validation since if the form is invalid,
        #   it means someone is likely trying to hack ratings. Ignore it.
        if form.is_valid():
            rating_value = request.POST["value"]
            # handle both anonymous session and authenticated users
            user = UserOrAnon.from_request(request)
            new_rating = DerpRating.create_or_update(
                user, self.derp, rating_value
            )
            if not user.is_anon:
                user.obj.profile.increment_n_derps_rated()
            return fresh_random_derp_view(self.request)
        else:
            # rating is invalid/has been tampered with
            return redirect(self.derp.get_absolute_url())


rate_derp_view = RateDerpView.as_view()


# --------------------------- Vote for Derp Rating --------------------------- #
# def rate_view(request, derp_uuid):
#   """
#   User is casting a new vote for a Derp rating.
#     - Validates the vote and casts it to the rating, updating the Derp
#       in the process
#     - Redirects the user to a new random derp from the db (to-do: pick from
#       Derp objects the user has not yet voted on)
#   """
#   derp = get_object_or_404(Derp, uuid=derp_uuid)
#   if request.method == 'POST':
#     rating = request.POST['rating']
#     # check for existing vote
#     vote = Vote.get_existing_or_none(derp, request)
#     if vote is None:
#       # create a new vote
#       if request.user.is_authenticated:
#         # User vote:
#         vote = Vote (
#           user=request.user, is_anonymous=False,
#           derp=get_object_or_404(Derp, uuid=derp_uuid),
#           weight=1, rating=rating
#         )
#       else:
#         # anon user session_id vote:
#         vote = Vote (
#           user = None, is_anonymous=True,
#           session_id=get_or_create_anon_id(request),
#           derp=get_object_or_404(Derp, uuid=derp_uuid),
#           weight=1, rating=rating
#         )
#     else:
#       # remove existing vote's influence
#       vote.remove()
#       # now update it
#       vote.rating = int(rating)
#     # save to db
#     vote.save()
#     # apply vote to Derp
#     vote.apply()
#     # TODO: once user profiles are implemented
#     # increment_user_vote_count(request.user)
#     # let the user know they voted
#     messages.success(request, f'{ derp.name } thanks you!')
#     # redirect to a new randomly selected derp, or to the noderps
#     # page if the user has exhausted all fresh derps to vote on
#     random_derp = Derp.get_fresh_or_none(request)
#     if random_derp is not None:
#       return redirect(f"/derp/{str(random_derp.uuid)}")
#     else:
#       return redirect('noderps')
#   else:
#     # GET request, so just return to the derp's page.
#     return redirect(f"/derp/{str(derp.uuid)}")

backend/ratemyderp/users/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    ListView,
    DetailView,
    RedirectView,
    CreateView,
    UpdateView,
)

from ratemyderp.users.models import DerpUser


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse(
            "users:detail", kwargs={"username": self.request.user.username}
        )


user_redirect_view = UserRedirectView.as_view()

backend/ratemyderp/templates/partials/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" prefix="og: https://ogp.me/ns#">
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  {# OpenGraph metadata - req'd fields #}
  <meta property="og:title" content="{% block meta_title %}{% endblock meta_title %}"/>
  <meta property="og:type" content="{% block meta_type %}{% endblock meta_type %}"/>
  <meta property="og:image" content="{% block meta_image %}{% endblock meta_image %}"/>
  <meta property="og:url" content="{{ BASE_URL }}{% block meta_url %}{{ request.path }}{% endblock meta_url %}"/>
  {# addt'l OG meta #}
  <meta property="og:description" content="{% block meta_desc %}{% endblock meta_desc %}"/>
  <meta property="og:site_name" content="{% block meta_site %}RateMyDerp!{% endblock meta_site %}"/>
  {# extra OG meta #}
  {% block meta_extra %}{% endblock meta_extra %}
  
  <title>{% block title %}{% endblock title %} | Rate My Derp!</title>
  <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
  {% include 'partials/_styles.html' %}

  <body class="app__root">
    <div class="app__container">
      {% include 'partials/_topnav.html' %}

      <div class="app__backing-grid" id="app-backing-grid">
        <main 
          id="app-view-container"
          class={% block main_classes %}{%endblock main_classes %}
        >
        {% include 'partials/_messages.html' %}
        {% block main %}{% endblock main %}
        </main>
      </div>

      {% include 'partials/_bottomnav.html' %}
    </div>
  </body>
  {% include 'partials/_scripts.html' %}
  {% block extra_scripts %}{% endblock extra_scripts %}
</html>

backend/ratemyderp/templates/partials/_bottomnav.html
{# Bottom Navbar #}
<nav class="app__btm-nav btm-nav">
  <a href="{% url 'go-rate' %}" 
    class="icon-btn btn--secondary {% if request.path == noderps %}icon-btn--active{% endif %}"
    >
    <div class="icon-btn__icons">
      <span class="icon-btn__icons--base material-icons material-icons-outlined"
        >grade</span
      >
      <span class="icon-btn__icons--hover material-icons">grade</span>
    </div>
    <span class="icon-btn__text"> go rate </span>
  </a>
  <a href="{% url 'derp:submit' %}" 
    class="icon-btn btn--secondary {% if request.resolver_match.url_name == submit2123 %}icon-btn--active{% endif %}"
    >
    <div class="icon-btn__icons" style="left: -5%">
      <span class="icon-btn__icons--base material-icons material-icons-outlined"
        >add_a_photo</span
      >
      <span class="icon-btn__icons--hover material-icons">add_a_photo</span>
    </div>
    <span class="icon-btn__text"> submit </span>
  </a>
  <a href="{% url 'top10' %}" class="icon-btn btn--secondary">
    <div class="icon-btn__icons">
      <span class="icon-btn__icons--base material-icons material-icons-outlined"
        >emoji_events</span
      >
      <span class="icon-btn__icons--hover material-icons">emoji_events</span>
    </div>
    <span class="icon-btn__text"> top 10 </span>
  </a>
</nav>

backend/ratemyderp/templates/partials/_messages.html
{% if messages %}
<ul class="toast__group">
  {% for message in messages %}
    <li class="card toast {% if message.tags %} {{ message.tags}} {% endif %}">
      {{ message }}
    </li>
  {% endfor %}
</ul>

{% endif %}

{% comment %} <ul class="toast__group">
  <li class="card toast card--secondary">
    Eiusmod dolore non qui sint deserunt tempor anim dolore magna id esse cillum.
  </li>
  <li class="card toast card--warning">
    Enim Lorem commodo eu nulla nulla ullamco.
  </li>
  <li class="card toast card--error">
    Dolor ad aute ex ut mollit nulla nulla.
  </li>
  <li class="card toast card--tertiary">
    Ipsum nostrud sit aute quis consectetur.
  </li>

</ul> {% endcomment %}

backend/ratemyderp/templates/partials/_scripts.html
{% load static %}
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/CustomEase.min.js"
  integrity="sha512-Av7Xa4snIobw1rWLKoVtFpsyIDVpNKj7QOTSKD+7xZxqeuXvMPwpwoq91zs4rw138w0pUhm8YVL6jKko34qmMA=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"
></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
<script src="{% static 'bundled/main.bundled.js' %}"></script>

backend/ratemyderp/templates/partials/_styles.html
{% load static %}
<!-- ---------------------------- Google Fonts ----------------------------- -->
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;1,600&family=Poppins:wght@500&display=swap"
  rel="stylesheet"
/>
<!-- --------------------------- Material Icons ---------------------------- -->
<link
  href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined"
  rel="stylesheet"
/>
<!-- ---------------------- FontAwesome Animal Icons ----------------------  -->
<script src="https://kit.fontawesome.com/7c1d3e511c.js" crossorigin="anonymous"></script>
<!-- ------------------------------ Local CSS ------------------------------ -->
<link rel="stylesheet" href="{% static 'bundled/main.bundled.css' %}" />

backend/ratemyderp/templates/partials/_topnav.html
{% load static %}
<!-- ----------------------------- Top Navbar ------------------------------ -->
<nav class="app__top-nav top-nav">
  <h1 class="top-nav__logo">
    <a href="{% url 'go-rate' %}">
      <img src="{% static 'svg/logo.svg' %}" alt="Rate My Derp! logo" />
    </a>
  </h1>
  <button
    class="top-nav__menu-btn btn btn--trans btn--is-square"
    id="main-menu-open"
  >
    <span class="material-icons">menu</span>
  </button>
  {% comment %} Main Menu {% endcomment %}
  <section class="main-menu" id="main-menu">
    <header class="main-menu__titlebar">
      <a href="{% url 'go-rate' %}" class="main-menu__logo">
        <img src="{% static 'svg/logo.svg' %}" alt="Rate My Derp! logo" />
      </a>
      <hr class="divider divider--has-responsive-margin" />
    </header>
    {% if user.is_authenticated %}
      <header class="main-menu__userbar" id="main-menu__top-row">
        <img
          src="{% if user.profile.avatar == '' %}{% static 'svg/user-img.svg' %}{% else %}{{ user.profile.avatar.url }}{% endif %}"
          alt="image of {{ user.username }}"
          class="main-menu__user-image"
        />
        <div class="main-menu__user-text">
          <span>logged in <br />as</span>
          <a href="{{ user.get_absolute_url }}" class="main-menu__user-text--name">{{ user.username }}</a>
        </div>
      </header>
    {% else %}
      <header class="main-menu__account-btns" id="main-menu__top-row">
        <a href="{% url 'account_signup' %}" class="btn btn--secondary">Sign Up</a>
        <a href="{% url 'account_login' %}" class="btn btn--primary m-t-sm">Login</a>
        <hr class="divider divider--has-responsive-margin" />
      </header>
    {% endif %}
    <ul class="main-menu__list">
      {% if user.is_authenticated %}
        <li class="menu-item">
          <hr class="divider divider--has-responsive-margin" />
        </li>
        <li class="menu-item">
          <a href="{{ user.get_absolute_url }}" class="menu-item__link">
            <span class="material-icons material-icons-outlined"> person </span>
            my profile
          </a>
        </li>
        <li class="menu-item">
          <a href="{% url 'profile:settings' %}" class="menu-item__link">
            <span class="material-icons"> settings </span>
            settings
          </a>
        </li>
        <li class="menu-item">
          <a href="{% url 'account_logout' %}" class="menu-item__link">
            <span class="material-icons material-icons-outlined"> logout </span>
            logout
          </a>
        </li>
        <li class="menu-item">
          <hr class="divider divider--has-responsive-margin" />
        </li>
      {% endif %}
      <li class="menu-item">
        <a href="{% url 'go-rate' %}" class="menu-item__link">
          <span class="material-icons material-icons-outlined"> grade </span>
          go rate
        </a>
      </li>
      <li class="menu-item">
        <a href="{% url 'derp:submit' %}" class="menu-item__link">
          <span class="material-icons material-icons-outlined">
            add_a_photo
          </span>
          submit
        </a>
      </li>
      <li class="menu-item">
        <a href="{% url 'top10' %}" class="menu-item__link">
          <span class="material-icons material-icons-outlined">
            emoji_events
          </span>
          top 10
        </a>
      </li>
      <li class="menu-item">
        <a href="{% url 'about' %}" class="menu-item__link">
          <span class="material-icons material-icons-outlined">
            help_outline
          </span>
          about
        </a>
      </li>
      <li class="menu-item">
        <hr class="divider divider--has-responsive-margin" />
      </li>
    </ul>
    <header class="main-menu__footerbar">
      <button class="btn btn--trans btn--is-square" id="main-menu-close">
        <span class="material-icons">expand_less</span>
      </button>
    </header>
  </section>
</nav>