backend/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views import defaults as default_views

urlpatterns = [
    # admin
    path(settings.ADMIN_URL, admin.site.urls),
    # user and account mgmt
    path("user/", include("ratemyderp.users.urls")),
    path("accounts/", include("allauth.urls")),
    # ratemyderp apps
    path("", include("ratemyderp.pages.urls")),
    path("derp/", include("ratemyderp.derps.urls")),
    path("rate/", include("ratemyderp.rating.urls")),
    path("profile/", include("ratemyderp.profiles.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns

backend/ratemyderp/derps/urls.py
from django.urls import path
from ratemyderp.derps.views import (
    derp_detail_view,
    derp_create_view,
    derp_delete_view,
    derp_share_view,
)

app_name = "derp"
urlpatterns = [
    path(route="<uuid:pk>", view=derp_detail_view, name="detail"),
    path(route="submit", view=derp_create_view, name="submit"),
    path(route="<uuid:pk>/delete", view=derp_delete_view, name="delete"),
    path(route="<uuid:pk>/share", view=derp_share_view, name="share"),
]

backend/ratemyderp/pages/urls.py
from django.urls import path
from ratemyderp.pages.views import noderps_page_view, about_page_view
from ratemyderp.derps.views import top10_derps_view
from ratemyderp.rating.views import go_rating_view

urlpatterns = [
    path("noderps", noderps_page_view, name="noderps"),
    path("top10", top10_derps_view, name="top10"),
    path("", go_rating_view, name="go-rate"),
    path("about", about_page_view, name="about"),
]

backend/ratemyderp/rating/urls.py
from django.urls import path
from django.conf import settings

from ratemyderp.rating.views import rate_derp_view, fresh_random_derp_view

app_name = "rating"
urlpatterns = [
    path(route="<uuid:derp_uuid>", view=rate_derp_view, name="rate"),
]

if settings.TEST_CONF:
    # only create URL route for fresh derp for testing
    urlpatterns += [
        path(route="fresh", view=fresh_random_derp_view, name="fresh"),
    ]

backend/ratemyderp/users/urls.py
from django.urls import path, include
from ratemyderp.users.views import user_redirect_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
]

backend/ratemyderp/derps/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.shortcuts import get_object_or_404
from random import choice
from model_utils.models import TimeStampedModel
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from dateutil.relativedelta import relativedelta
from datetime import datetime, timezone
from math import floor

from ratemyderp.utils.sessions import UserOrAnon
from ratemyderp.derps.validators import validate_age, validate_derp_name

import uuid


# -------------------------------- Derp Model -------------------------------- #
class Derp(TimeStampedModel):
    """
    Models each Derp entry in the database.
    """

    # derp PK is UUID4
    uuid = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False
    )
    # user who submitted this derp
    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    # the derp's name
    name = models.CharField(max_length=50, validators=[validate_derp_name])
    # species choices
    class Species(models.TextChoices):
        CANINE = "DOG", "Canine"
        FELINE = "CAT", "Feline"
        REPTILE = "REP", "Reptile"
        FISH = "FSH", "Fishy"
        SMALL = "SML", "Lil' Thing"
        BIRB = "BRB", "Birb"
        OTHER = "OTH", "Other"

    # derp species
    species = models.CharField(
        "Species", max_length=3, choices=Species.choices, default=Species.OTHER
    )

    # age in years
    age_when_added = models.FloatField(validators=[validate_age])
    # biography text
    bio = models.TextField(max_length=200, blank=True)
    # derp image
    # image = models.ImageField(upload_to="images/%Y/%m/%d/")
    image = ProcessedImageField(
        upload_to="derps/%Y/%m/%d/",
        processors=[ResizeToFill(1080, 1080)],
        format="JPEG",
        options={"quality": 70},
    )

    # derp statistics
    rank = models.IntegerField(default=0, editable=False, blank=True)
    n_shares = models.IntegerField(default=0, editable=False, blank=True)
    n_awards = models.IntegerField(default=0, editable=False, blank=True)
    n_flags = models.IntegerField(default=0, editable=False, blank=True)
    # visits
    n_visits = models.IntegerField(default=0, editable=False, blank=True)
    n_user_visits = models.IntegerField(default=0, editable=False, blank=True)
    n_anon_visits = models.IntegerField(default=0, editable=False, blank=True)
    # rating fields
    rating_n_votes = models.IntegerField(default=0, editable=False, blank=True)
    """total number of rating votes cast"""
    rating_acc = models.IntegerField(default=0, editable=False, blank=True)
    """accumulator for rating calculations"""
    rating_val = models.FloatField(default=0, blank=True, editable=False)
    """the cumulative average rating value at this point in time"""

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("derp:detail", kwargs={"pk": self.uuid})

    def species_icon(self):
        """
        String rep'n of Derp's species icon
        """
        return Derp.species_to_icon_str(self.species)

    def get_date_created_pretty(self):
        return self.created.strftime("%b %e %Y")

    # --------------------------------- Derp Age --------------------------------- #
    def get_age(self):
        """
        Return the current age in years of the Derp based on its age when created.
        """
        return round(
            ((datetime.now(timezone.utc) - self.get_birthday()).days / 365),
            2,
        )

    def get_birthday(self):
        """
        Returns a datetime instance representing the birthday.
        Approximated based on the user-submitted age during creation.
        """
        return self.created + relativedelta(months=-self.age_when_added * 12)

    def get_age_display(self):
        """
        Formats the age of the Derp into a display string of the form
        "00y 00mo old" for use in templates.
        """
        age_years = self.get_age()
        y = floor(age_years)
        m = (age_years - y) * 12
        y_old = f"{int(y)}y " if y != 0 else ""
        m_old = f"{int(m)}mo " if m != 0 else ""
        return y_old + m_old + "old"

    # ---------------------------- Add/Subtract Rating --------------------------- #
    def apply_rating(self, rating, weight):
        """
        Apply a rating to this Derp, generically.
        Sign of weight implies add/subtract influence to rating.
        """
        # 1. add rating to accumulator and increment count
        n_votes = self.rating_n_votes + (1 if weight > 0 else -1)
        n_votes = 0 if n_votes < 0 else n_votes
        rating_acc = self.rating_acc + int(rating) * weight
        if rating_acc < 0:
            rating_acc = 0
        # 2. compute new rating
        new_rating = 0 if n_votes == 0 else (float(rating_acc) / n_votes)
        # 3. update & save the Derp
        self.rating_n_votes = n_votes
        self.rating_acc = rating_acc
        self.rating_val = new_rating
        self.save()
        return new_rating

    def add_rating(self, rating, weight=1):
        """
        Adds a vote's influence to the Rating calculation.
        """
        return self.apply_rating(rating, weight=abs(weight))

    def subtract_rating(self, rating, weight=1):
        """
        Subtracts a vote's influence from the Rating calculation.
        """
        return self.apply_rating(rating, weight=-abs(weight))

    # --------------------------- Increment Visit Count -------------------------- #
    def increment_visit_count(self, user_or_anon):
        """
        Increments this Derp's visit count stat.
        Categorises visits based on whether they are registered or anon users.
        """
        UserOrAnon.assert_param_type(user_or_anon)
        self.n_visits += 1
        if user_or_anon.is_anon:
            self.n_anon_visits += 1
        else:
            self.n_user_visits += 1
        self.save()

    # --------------------------- Increment Share Count -------------------------- #
    def increment_share_count(self):
        """
        Increments the share counter for this Derp.
        """
        self.n_shares += 1
        self.save()

    # --------------------------------- Set Rank --------------------------------- #
    def set_rank(self, new_rank):
        """
        Updates the positional rank stat for this Derp.
        Only writes Derp object back to db if rank has changed.
        """
        rank = int(new_rank)
        if rank != self.rank:
            self.rank = rank
            self.save()

    @classmethod
    def get_by_uuid(cls, uuid):
        """
        Query a given Derp by uuid.
        ### DO NOT USE OUTSIDE OF VIEWS!
        """
        return get_object_or_404(cls, uuid=uuid)

    @classmethod
    def species_to_icon_str(cls, species):
        """Returns FontAwesome icon string to use from a Derp.Species value"""
        Opt = cls.Species
        match species:
            case Opt.CANINE:
                return "fa-solid fa-dog"
            case Opt.FELINE:
                return "fa-solid fa-cat"
            case Opt.REPTILE:
                return "fa-solid fa-dragon"
            case Opt.FISH:
                return "fa-solid fa-fish"
            case Opt.SMALL:
                return "fa-solid fa-bug"
            case Opt.BIRB:
                return "fa-solid fa-kiwi-bird"
            case Opt.OTHER:
                return "fa-solid fa-circle-question"
            case _:
                return "fa-solid fa-circle-question"

    @classmethod
    def get_derps_already_rated(cls, user_or_anon):
        """
        Gets all the Derps a user has already rated.
        Returns a queryset.
        """
        UserOrAnon.assert_param_type(user_or_anon)
        return (
            cls.objects.filter(derprating__session_id=user_or_anon.obj)
            if user_or_anon.is_anon
            else cls.objects.filter(derprating__user=user_or_anon.obj)
        )

    @classmethod
    def get_fresh_or_none(cls, user_or_anon):
        """
        Retrieves a random "fresh" Derp from the database.
        Returns a Derp object or None.
        If there are no derps which have not been voted on by the request.user left,
        we return None instead of a Derp object.
        """
        UserOrAnon.assert_param_type(user_or_anon)

        # 1. query all the derps this user has rated
        derps_already_rated = cls.get_derps_already_rated(user_or_anon)
        # 2. query derps excluding ones in derps_voted_on
        fresh_derps = cls.objects.all().difference(derps_already_rated)
        # 3. we return none if the user has rated every derp in the db;
        #   else a random fresh one
        fresh_derp = choice(fresh_derps) if fresh_derps.exists() else None
        user_or_anon.set_next_derp_to_rate(fresh_derp)
        return fresh_derp

    @classmethod
    def update_all_rankings(cls):
        """
        Update the positional ranking stat of all Derps in the DB.
        Should be called periodically to re-compute derp rankings.
        """
        derps = cls.objects.all().order_by("-rating_val")
        for i, derp in enumerate(derps):
            derp.set_rank(i + 1)

backend/ratemyderp/rating/forms.py
from django.forms import ModelForm, NumberInput

from ratemyderp.rating.models import DerpRating


class RatingForm(ModelForm):
    class Meta:
        model = DerpRating
        fields = [
            "value",
        ]
        widgets = {
            "value": NumberInput(
                attrs={"type": "range", "step": "1", "min": "1", "max": "10"}
            )
        }

backend/ratemyderp/derps/views.py
from django.views.generic import DetailView, CreateView, DeleteView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404

from ratemyderp.derps.models import Derp
from ratemyderp.derps.forms import DerpForm
from ratemyderp.rating.models import DerpRating
from ratemyderp.utils.sessions import UserOrAnon


class DerpCreateView(LoginRequiredMixin, CreateView):
    form_class = DerpForm
    model = Derp

    # inject owner fkey after form validation occurs
    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


derp_create_view = DerpCreateView.as_view()


class DerpDetailView(DetailView):
    model = Derp

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # add existing rating from this user to template context, if it exists
        if self.request.user is not None:
            existing_rating = DerpRating.get_existing_or_none(
                self.request.user, self.get_object()
            )
            ctx["user_rating"] = (
                existing_rating.value if existing_rating is not None else None
            )
        return ctx

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        # increment visit counter for this Derp
        user = UserOrAnon.from_request(request)
        self.object.increment_visit_count(user)
        return res


derp_detail_view = DerpDetailView.as_view()


class DerpShareView(DetailView):
    model = Derp
    template_name = "derps/derp_share.html"

    def get(self, request, *args, **kwargs):
        res = super().get(request, *args, **kwargs)
        # increment the share counter for this Derp
        self.get_object().increment_share_count()
        return res


derp_share_view = DerpShareView.as_view()


class Top10DerpsView(ListView):
    model = Derp
    template_name = "derps/derps_top10.html"
    queryset = Derp.objects.all().order_by("-rating_val")[:10]
    context_object_name = "derps"


top10_derps_view = Top10DerpsView.as_view()


class DerpDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Derp
    template_name = "derps/derp_delete.html"
    success_message = ""

    def get_object(self, queryset=None):
        derp = super(DerpDeleteView, self).get_object()
        self.user = self.request.user
        if derp.owner != self.user:
            raise Http404
        return derp

    def get_success_url(self):
        return self.user.get_absolute_url()

    def get_success_message(self, cleaned_data):
        return f"Deleted {self.object.name} successfully."


derp_delete_view = DerpDeleteView.as_view()

backend/ratemyderp/pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"


home_page_view = HomePageView.as_view()


class NoDerpsPageView(TemplateView):
    template_name = "pages/noderps.html"


noderps_page_view = NoDerpsPageView.as_view()


class AboutPageView(TemplateView):
    template_name = "pages/about.html"


about_page_view = AboutPageView.as_view()

backend/ratemyderp/profiles/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, UpdateView
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin

from ratemyderp.profiles.models import DerpUserProfile
from ratemyderp.profiles.forms import DerpUserProfileForm
from ratemyderp.derps.models import Derp

User = get_user_model()


class UserProfileView(ListView):
    model = Derp
    template_name = "profiles/profile_detail.html"
    context_object_name = "derps"
    paginate_by = 6

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = get_object_or_404(User, username=kwargs["username"])
        self.queryset = Derp.objects.filter(owner=self.user)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # we add the user's profile to the context (which already
        # contains their paginated derplist)
        ctx["profile"] = DerpUserProfile.objects.get(user=self.user)
        return ctx


user_profile_view = UserProfileView.as_view()


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):

    model = DerpUserProfile
    template_name = "profiles/profile_update.html"
    form_class = DerpUserProfileForm
    context_object_name = "profile"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.user = request.user

    def get_object(self):
        profile = get_object_or_404(DerpUserProfile, user=self.user)
        return profile


user_profile_update_view = UserProfileUpdateView.as_view()

backend/ratemyderp/templates/derps/derp_delete.html
{% extends 'partials/_base.html' %}

{% block title %}Delete Derp{% endblock title %}

{% block main_classes %}
  "app__view view-container view-container--is-v-center"
{% endblock main_classes %}

{% block main %}
  <h2 class="view-title">Confirm Delete</h2>
  <form 
    class="form-container form-container--is-panel"
    method="POST"  
  >
    {% csrf_token %}
    <p>
      Are you certain you want to delete <a href="{{ object.get_absolute_url }}" class="link"><strong>{{ object }}</strong></a>? This cannot be undone.
    </p>
    {{ form }}
    <button type="submit" class="btn btn--primary btn--is-submit">Yes, Delete</button>
        
  </form>
  {# text below form panel #}
  <h4 class="subtitle">
    Made a mistake?
    <a href="{% url 'derp:detail' object.uuid %}" class="link">Take me back</a>
  </h4>
{% endblock main %}

backend/ratemyderp/templates/derps/derp_detail.html
{% extends 'partials/_base.html' %}
{% load static %}
{% load humanize %}

{% block title %}Rate {{ derp.name }}{% endblock title %}

{% block main_classes %}"app__view"{% endblock main_classes %}

{% block meta_title %}{{ derp.name | truncatewords:2 }} - Rated {{ derp.rating_val | floatformat:2 }} - Rate My Derp!{% endblock meta_title %}
{% block meta_type %}website{% endblock meta_type %}
{% block meta_image %}{{ BASE_URL }}{{ derp.image.url }}{% endblock meta_image %}
{% block meta_desc %}Rated {{ derp.rating_val | floatformat:2 }}/10 derpy. Do you agree? Vote for {{derp.name}}'s derpiness now!{% endblock meta_desc %}
{% block meta_extra %}
  <meta property="og:image:type" content="image/jpeg"/>
  <meta property="og:image:width" content="{{ derp.image.width }}"/>
  <meta property="og:image:height" content="{{ derp.image.height }}"/>
{% endblock meta_extra %}


{% block main %}
  <div class="rate-view__grid">
    <!-- Titlebar (only visible on non-mobile vw) -->
    <h2 class="rate-view__titlebar title">{{ derp.name }}</h2>
    <!-- Detail Pane Derp Stats -->
    <div class="detailpane rate-view__stats" id="derp-detail-pane">
      <header class="detailpane__bar flexbar flexbar--has-button">
        <div class="statsbar statsbar--is-derp flexbar__body">
          <header class="statsbar__left">
            <h2 class="statsbar__name">{{ derp.name }}</h2>
            <span class="statsbar__species"> {{ derp.get_species_display }}</span>
          </header>
          <div class="statsbar__right">
            <span class="statsbar__rank stat">
              <span class="material-icons">trending_up</span>
              {{ derp.rank | ordinal}}
            </span>
            <span class="statsbar__rating stat">
              <span class="material-icons">grade</span>
              {{ derp.rating_val | floatformat:2 }}
            </span>
          </div>
        </div>
        <button
          class="flexbar__btn btn btn--is-square btn--bg-2"
          id="detail-pane-open"
        >
          <span class="material-icons">more_vert</span>
        </button>
      </header>
      {# Body of Detail Pane #}
      <section class="detailpane__body card card--bg-2">
        <div
          class="flexbar flexbar--has-button flexbar--bg-3 detailpane__titlebar"
        >
          <h2 class="flexbar__title detailpane__titlebar--name">{{ derp.name }}</h2>
          <h2 class="flexbar__title detailpane__titlebar--title">Derp Stats</h2>
          <button
            class="flexbar__btn btn btn--trans detailpane__btn"
            id="detail-pane-close"
          >
            <span class="material-icons">close</span>
          </button>
        </div>
        <div class="flexbar">
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">trending_up</span>
            {{ derp.rank | ordinal}} place
          </span>
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">grade</span>
            {{ derp.rating_val | floatformat:2 }} rating
          </span>
        </div>
        <div class="flexbar">
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">done</span>
            {{ derp.rating_n_votes }} votes
          </span>
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">watch_later</span>
            {{ derp.created | naturaltime }}
          </span>
        </div>
        {% if derp.bio != '' %}
          <div class="card card--bg-3 card--is-text-only">
            <h4 class="card__title">Biography</h4>
            <div class="card__body">
              <p>
                {{ derp.bio }}
              </p>
            </div>
          </div>
        {% endif %}
        <div class="flexbar">
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">child_care</span>
            {{ derp.get_age_display }}
          </span>
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">pets</span>
            {{ derp.get_species_display }}
          </span>
          <span class="stat stat--is-panel is-bg-3 flexbar__body">
            <span class="material-icons">emoji_events</span>
            {{ derp.n_shares }} shares
          </span>
        </div>
        {% if derp.owner == user %}
          <a href="{% url 'derp:delete' derp.uuid %}"class="btn btn--primary m-med">
            <span class="material-icons">close</span>
            Delete Derp
          </a>
        {% else %}
          {% comment %} 
          <button class="btn btn--bg-3 m-med detailpane__btn">
            <span class="material-icons">flag</span>
            Report Content
          </button>
          {% endcomment %}
        {% endif %}
      </section>
    </div>

    <!-- ----------------------------- Derp Image ------------------------------ -->
    <div class="rate-view__image">
      <img src="{{ derp.image.url }}" alt="a derpy {{ derp.get_species_display }} named {{derp.name}}" />
    </div>

    <!-- ---------------------------- User StatsBar ---------------------------- -->
    <div class="rate-view__user flexbar flexbar--has-button">
      <div class="statsbar statsbar--is-user flexbar__body">
        <a href="{{ derp.owner.get_absolute_url }}" class="statsbar__image">
          <img 
            src="{% if derp.owner.profile.avatar == '' or derp.owner.profile.is_private %}{% static 'svg/user-img.svg' %}{% else %}{{ derp.owner.profile.avatar.url }}{% endif %}"
            alt="image of {{ derp.owner.username }}" 
          >
        </a>
        <div class="statsbar__left">
          <header>
            <a href="{{ derp.owner.get_absolute_url }}">
              <h3 class="statsbar__name">
                  {{ derp.owner.username }}
              </h3>
            </a>
            <span class="statsbar__added">added on {{ derp.get_date_created_pretty}}</span>
          </header>
        </div>
      </div>
      <a class="flexbar__btn btn btn--secondary" href="{{derp.get_absolute_url}}/share">
        <span class="material-icons">share</span>
        Share
      </a>
    </div>

    {# Rate This Derp! #}
    <form action="{% url 'rating:rate' derp.uuid %}" class="rate-view__rate rating__panel" method="POST">
      {% csrf_token %}
      <h3 class="subtitle">Rate this derp to see a new one!</h3>
      <!-- Rating Slider Group -->
      <div class="rating__group" id="rating-slider">
        <div class="rating__scale"></div>
        <input
          type="range"
          name="value"
          id="value"
          min="1"
          max="10"
          {% if user_rating %}value="{{ user_rating }}"{% endif %}
          class="rating__input"
        />
        <div class="rating__value">
          {% if ctx.rating %}
            {{ ctx.rating }}
          {% endif %}
        </div>
      </div>
      <!-- Rating Submit Button -->
      <button class="btn btn--primary btn--is-large" type="submit">Rate!</button>
    </form>
    <footer class="rate-view__footer">
      {% comment %}
      <button class="btn btn--bg-2 m-med">
        <span class="material-icons">flag</span>
        Report Content
      </button>
      {% endcomment %}
    </footer>
  </div>
{% endblock main %}

backend/ratemyderp/templates/derps/derp_form.html
{% extends 'partials/_base.html' %}

{% load derp_tags %}

{% block title %}Submit Your Derp{% endblock title %}

{% block main_classes %}"app__view form-view"{% endblock main_classes %}

{% block main %}
  <form
    method="POST"
    class="form-container"
    action="{% url 'derp:submit' %}"
    enctype="multipart/form-data"
  >
    {% csrf_token %}
    <!-- Title -->
    <h2 class="view-title">Create Derp</h2>

    {# general errors #}
    {% if form.non_field_errors %}
      <section class="card card--error card--is-text-only">
        <h4 class="card__title">Error</h4>
        <ul class="card__body">
          {% for error in form.non_field_errors %}
            <li class=>
              {{ error }}
            </li>
          {% endfor %}
        </ul>
      </section>
    {% endif %}

    <!-- Derp Name -->
    {# Name #}
    <div class="input__field input__field--text">
      <div class="input__group">
        <label for="{{ form.name.id_for_label }}" class="input__label">{{form.label_tag}}</label>
        {{ form.name }}
      </div>
      {% with form.name.errors as errors %}
        <span class="input__helper">
          {% if errors %}
            {{ errors }}
          {% else %}
            What do you call this derpy creature?
          {% endif %}
        </span>
      {% endwith %}
    </div>

    {# Species Radio Chooser #}
    <div class="input__field input__field--radio">
      <div class="input__group">
        <label for="species" class="input__label">Species</label>
        <div class="radio__choices">
          {% for radio in form.species %}
            <label for="{{ radio.id_for_label }}" class="species">
              {{ radio.tag }}
              <i class="species__icon fa-xl {{ radio.data.value|derp_species_icon }}"></i>
              <div class="species__choice-text">
                {{ radio.data.label }}
              </div>
            </label>
          {% endfor %}
        </div>
        {% with form.species.errors as errors %}
          <span class="input__helper">
            {% if errors %}
              {{ errors }}
            {% endif %}
          </span>
        {% endwith %}
      </div>
    </div>

    {# Biography Text #}
    <div class="input__field input__field--textarea">
      <div class="input__group">
        <label for="{{ form.bio.id_for_label }}" class="input__label">Biography</label>
        {{ form.bio }}
      </div>
      {% with form.bio.errors as errors %}
        <span class="input__helper">
          {% if errors %}
            {{ errors }}
          {% else %}
          Tell us a little story about that derp.
          {% endif %}
        </span>
      {% endwith %}
    </div>

    {# Age #}
    <div class="input__field input__field--text">
      <div class="input__group">
        <label for="{{ form.age_when_added.id_for_label }}" class="input__label">Age</label>
        {{ form.age_when_added }}
      </div>
      {% with form.age_when_added.errors as errors %}
        <span class="input__helper">
          {% if errors %}
            {{ errors }}
          {% else %}
          Enter their age in years
          {% endif %}
        </span>
      {% endwith %}
    </div>

    {# Image Upload #}
    <div class="input__field input__field--image">
      <div class="input__group">
        <label for="{{ form.image.id_for_label }}" class="input__label">Photo</label>
        {{ form.image }}
        {% with form.image.errors as errors %}
          <span class="input__helper">
            {% if errors %}
              {{ errors }}
            {% else %}
            Square ratio images are best. Cropping will occur otherwise.
            {% endif %}
          </span>
        {% endwith %}
      </div>
    </div>

    <button class="btn btn--primary btn--is-submit" type="submit" value="Submit">
      Submit Derp
    </button>
  </form>
{% endblock main %}